variables:
- name: one
  value: initialValue 

steps:
  - script: |
      echo "Line1 of Script - " ${{ variables.one }} # outputs initialValue
      echo "Line2 of Script - " $(one)
    displayName: First variable pass
  - bash: echo "##vso[task.setvariable variable=one]secondValue"
    displayName: Set new variable value
  - script: |
      echo ${{ variables.one }} # outputs initialValue
      echo $(one) # outputs secondValue
    displayName: Second variable pass